### ISSUE TITLE
can't make test

### ISSUE THREAD

**Issue by WorshipSmeb** [upenn-acg/detTrace#280]
I am learning use dettrace, after build dettrace, I want to try test it ,so according to README.md I try make test but failed
the error is 
Makefile:177: recipe for target 'check-formatting' failed
make: *** [check-formatting] Error 123

I hope get help thanks

**Comment by gatoWololo** [comment]
Hello, I have played around with this a bit. The tests have... many issues. You're getting this error because you probably don't have clang-format installed. Even after installing and fixing there will be other issues. So it is very unlikely that the tests will ever all "pass" for you.
Two options:
- If you really want to continue running the tests I can walk though the steps to fix the issues.

OR
- You can try running a simple command like `./bin/dettrace -- ls -ahl` and see if that works. If that works, then you're pretty much set as far as using dettrace. I'd be happy to help with any issues you experience from here.

**Comment by WorshipSmeb** [comment]
> Hello, I have played around with this a bit. The tests have... many issues. You're getting this error because you probably don't have clang-format installed. Even after installing and fixing there will be other issues. So it is very unlikely that the tests will ever all "pass" for you.
> Two options:
> 
> * If you really want to continue running the tests I can walk though the steps to fix the issues.
> 
> OR
> 
> * You can try running a simple command like `./bin/dettrace -- ls -ahl` and see if that works. If that works, then you're pretty much set as far as using dettrace. I'd be happy to help with any issues you experience from here.

**Comment by WorshipSmeb** [comment]
Thanks for your answer，I know the reason why I can‘t make test，that is good。but when I continue learen using dettrace，I face a new problem。the description is as fellow：

first I built  the dettrace  on the /home/username/ Dettrace , and then use commands . /bin/dettrace -- make -C /home/username/dettrace-1 ， ./bin/dettrace - make -C /home /username/dettrace-2  , but when I used diffoscope to compare the executable file /home/username/dettrace-1/bin/dettrace and  /home/username/dettrace-2/bin/dettrace ,however they are not identical , and inconsistent information is the build directory was reported. I am using a virtual machine of ubuntu 18.04. on VM The kernel version is 5.4.0-52-generic x86_64 intel.

I don't use dettrace correctly or other things lead to this。I hope you can help me。thanks very much

**Comment by WorshipSmeb** [comment]
> Hello, I have played around with this a bit. The tests have... many issues. You're getting this error because you probably don't have clang-format installed. Even after installing and fixing there will be other issues. So it is very unlikely that the tests will ever all "pass" for you.
> Two options:
> 
> * If you really want to continue running the tests I can walk though the steps to fix the issues.
> 
> OR
> 
> * You can try running a simple command like `./bin/dettrace -- ls -ahl` and see if that works. If that works, then you're pretty much set as far as using dettrace. I'd be happy to help with any issues you experience from here.

Thanks for your answer，I know the reason why I can‘t make test，that is good。
